blank_issues_enabled: false
contact_links:
  - name: Discord community
    url: https://discord.com/invite/dwG9jPrhxB
    about: "Questions or general support are better suited for our Discord server."

